# Generated by Django 6.1 on 2026-09-02 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_facility_facility_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('order', models.PositiveIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('period_type', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('BIANNUAL', 'Biannual'), ('ANNUAL', 'Annual')], max_length=20)),
                ('period_number', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=100)),
                ('start_month', models.PositiveIntegerField()),
                ('end_month', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-year', 'start_month'],
                'constraints': [models.UniqueConstraint(fields=('year', 'period_type', 'period_number'), name='unique_assessment_period')],
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('REVIEWED', 'Reviewed'), ('APPROVED', 'Approved'), ('RETURNED', 'Returned')], default='DRAFT', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_assessments', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='core.facility')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='assessments.assessmentperiod')),
            ],
            options={
                'ordering': ['-period__year', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentThematicArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=500)),
                ('maximum_score', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('order', models.PositiveIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='thematic_areas', to='assessments.assessmentsection')),
            ],
            options={
                'ordering': ['section', 'order'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('question', models.TextField()),
                ('response_type', models.CharField(choices=[('YES_NO', 'Yes / No'), ('CHOICE', 'Multiple Choice'), ('NUMERIC', 'Numeric'), ('CALCULATION', 'Calculated'), ('CONDUCTED_CHECK', 'Conducted / Not Conducted')], default='YES_NO', max_length=30)),
                ('calculation_type', models.CharField(choices=[('NONE', 'No Calculation'), ('PERCENTAGE', 'Percentage'), ('RATIO', 'Numerator / Denominator'), ('PERIOD_MONTHS', 'Based on Period Months'), ('CUSTOM', 'Custom Calculation')], default='NONE', max_length=30)),
                ('maximum_score', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('help_text', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('thematic_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indicators', to='assessments.assessmentthematicarea')),
            ],
            options={
                'ordering': ['thematic_area__section', 'thematic_area__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='IndicatorOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('label', models.CharField(max_length=500)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('order', models.PositiveIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='assessments.assessmentindicator')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('numerator', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('denominator', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('calculated_score', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('conducted', models.BooleanField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='assessments.assessment')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='assessments.assessmentindicator')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessment_responses', to='assessments.indicatoroption')),
            ],
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.UniqueConstraint(fields=('facility', 'period'), name='one_assessment_per_facility_period'),
        ),
        migrations.AddConstraint(
            model_name='assessmentthematicarea',
            constraint=models.UniqueConstraint(fields=('section', 'code'), name='unique_thematic_area_code'),
        ),
        migrations.AddConstraint(
            model_name='assessmentindicator',
            constraint=models.UniqueConstraint(fields=('thematic_area', 'code'), name='unique_indicator_code'),
        ),
        migrations.AddConstraint(
            model_name='assessmentresponse',
            constraint=models.UniqueConstraint(fields=('assessment', 'indicator'), name='one_response_per_indicator'),
        ),
    ]
