# Generated by Django 6.1 on 2026-09-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_assessment_approval_comment_assessment_return_reason_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessment',
            options={'ordering': ['-period__year', '-period__start_month', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='assessmentindicator',
            options={'ordering': ['thematic_area__section__order', 'thematic_area__order', 'order', 'code']},
        ),
        migrations.AlterModelOptions(
            name='assessmentperiod',
            options={'ordering': ['-year', 'start_month', 'period_type', 'period_number']},
        ),
        migrations.AlterModelOptions(
            name='assessmentthematicarea',
            options={'ordering': ['section__order', 'order', 'code']},
        ),
        migrations.AlterModelOptions(
            name='indicatoroption',
            options={'ordering': ['order', 'code']},
        ),
        migrations.AddConstraint(
            model_name='indicatoroption',
            constraint=models.UniqueConstraint(fields=('indicator', 'code'), name='unique_indicator_option_code'),
        ),
    ]
