# Generated by Django 6.1 on 2026-09-02 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('unit_type', models.CharField(choices=[('COUNTRY', 'Country'), ('REGION', 'Region'), ('ZONE', 'Zone'), ('SUBCITY', 'Sub-city'), ('WOREDA', 'Woreda'), ('HOSPITAL', 'Hospital'), ('HEALTH_CENTER', 'Health Center'), ('OTHER', 'Other')], max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='core.organizationunit')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
