# Generated by Django 6.1 on 2026-09-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_facility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='facility_type',
            field=models.CharField(choices=[('SPECIAL_HOSPITAL', 'Special Hospital'), ('HEALTH_CENTER', 'Health Center')], max_length=30),
        ),
        migrations.AlterField(
            model_name='organizationunit',
            name='unit_type',
            field=models.CharField(choices=[('MINISTRY', 'Ministry of Health'), ('COUNTRY', 'Country'), ('REGION', 'Region'), ('ZONE', 'Zone'), ('SUBCITY', 'Sub-city'), ('WOREDA', 'Woreda'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
