# Generated by Django 6.1 on 2026-09-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_facility_facility_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationunit',
            name='unit_type',
            field=models.CharField(choices=[('MINISTRY', 'Ministry of Health'), ('REGION', 'Region'), ('ZONE', 'Zone'), ('SUBCITY', 'Sub-city'), ('WOREDA', 'Woreda'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
