# Generated by Django 6.1 on 2026-09-09 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_alter_organizationunit_unit_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('ASSESSMENT', 'Assessment'), ('LQAS', 'LQAS'), ('DASHBOARD', 'Dashboard'), ('REPORTS', 'Reports'), ('TECHNICAL', 'Technical Problem'), ('DATA', 'Data Quality'), ('OTHER', 'Other')], max_length=30)),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal'), ('IMPORTANT', 'Important'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20)),
                ('message', models.TextField()),
                ('sender_level', models.CharField(choices=[('FACILITY', 'Facility'), ('SUBCITY', 'Sub-city'), ('REGION', 'Region'), ('MINISTRY', 'Ministry')], max_length=20)),
                ('recipient_level', models.CharField(choices=[('SUBCITY', 'Sub-city'), ('REGION', 'Region'), ('MINISTRY', 'Ministry')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='PENDING', max_length=20)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feedback_received', to='core.organizationunit')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_feedback', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_feedback', to=settings.AUTH_USER_MODEL)),
                ('sender_facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feedback_sent', to='core.facility')),
                ('sender_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feedback_sent_from', to='core.organizationunit')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='feedback_fe_status_35d074_idx'), models.Index(fields=['priority'], name='feedback_fe_priorit_fbe607_idx'), models.Index(fields=['category'], name='feedback_fe_categor_9a32a3_idx'), models.Index(fields=['sender_level'], name='feedback_fe_sender__9ddd7d_idx'), models.Index(fields=['recipient_level'], name='feedback_fe_recipie_757ea0_idx'), models.Index(fields=['created_at'], name='feedback_fe_created_84c297_idx')],
            },
        ),
    ]
