# Generated by Django 6.1 on 2026-09-09 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_organizationunit_unit_type'),
        ('feedback', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='feedback.feedback'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['parent'], name='feedback_fe_parent__ff42d1_idx'),
        ),
    ]
