# Generated by Django 6.1 on 2026-09-09 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_organizationunit_unit_type'),
        ('feedback', '0002_feedback_parent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='recipient_facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feedback_received', to='core.facility'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='recipient_level',
            field=models.CharField(choices=[('FACILITY', 'Facility'), ('SUBCITY', 'Sub-city'), ('REGION', 'Region'), ('MINISTRY', 'Ministry')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['sender_facility'], name='feedback_fe_sender__dd9c47_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['recipient_facility'], name='feedback_fe_recipie_b442d2_idx'),
        ),
    ]
