# Generated by Django 6.1 on 2026-09-11 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_assessment_approval_comment_assessment_return_reason_and_more'),
        ('core', '0004_alter_organizationunit_unit_type'),
        ('feedback', '0003_feedback_recipient_facility_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feedback_messages', to='assessments.assessmentperiod'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='recipient_level',
            field=models.CharField(choices=[('FACILITY', 'Facility'), ('SUBCITY', 'Sub-city / Zone / Woreda'), ('REGION', 'Region'), ('MINISTRY', 'Ministry')], max_length=20),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='sender_level',
            field=models.CharField(choices=[('FACILITY', 'Facility'), ('SUBCITY', 'Sub-city / Zone / Woreda'), ('REGION', 'Region'), ('MINISTRY', 'Ministry')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['sender_organization'], name='feedback_fe_sender__eaf8f4_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['recipient_organization'], name='feedback_fe_recipie_9e697c_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['period'], name='feedback_fe_period__54e94e_idx'),
        ),
    ]
