# Generated by Django 6.1 on 2026-09-10 21:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_organizationunit_unit_type'),
        ('lqas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='lqasassessment',
            constraint=models.UniqueConstraint(fields=('facility', 'year', 'period'), name='unique_lqas_facility_year_period'),
        ),
    ]
